---

- name: Update the apt package index
  apt:
    update_cache: yes

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'gnupg2'
    - 'software-properties-common'

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Set up Docker stable repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce={{ docker_version }}
    state: present
    update_cache: yes

- name: Add vagrant user to docker group 
  user: 
    name: vagrant
    groups: docker
    append: yes

- name: Modify systemd unit file to add extra parameters
  template:
    src: 'lib/systemd/system/docker.service.j2'
    dest: '/lib/systemd/system/docker.service'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Reload systemd daemon for chages to take effect
  command: 'systemctl daemon-reload'
  notify:
    - Restart Docker
